// ova e json file so site menu items, pls ako neso menjas pisi mi - Gavro
const menu_items = [
    {
      "name": "Custom Omelet",
      "macedonian_name": "ОМЛЕТ ПО ИЗБОР",
      "details": "Customizable omelet with three eggs and ham.",
      "ingredients": ["3 eggs", "ham", "cheese", "yellow cheese"],
      "tags": ["breakfast", "customizable"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": ["kulen", "bacon", "mushrooms", "mozzarella", "pepper"],
      "price": 170,
      "image": "./picturesFoods/CustomOmelet.jpg"
    },
    {
      "name": "Bagel with Eggs",
      "macedonian_name": "ЃЕВРЕК СО ЈАЈЦА",
      "details": "Bagel with eggs, cheese, and fresh vegetables.",
      "ingredients": ["2 eggs", "bagel", "cheese", "tomato", "cucumber"],
      "tags": ["breakfast"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 160,
      "image": "./picturesFoods/Bagel with Eggs.jpg"
    },
    {
      "name": "Club Sandwich",
      "macedonian_name": "КЛУБ СЕНДВИЧ",
      "details": "Club sandwich with ham, kulen, cheese, and fries.",
      "ingredients": [
        "toast bread",
        "sour cream with dill",
        "yellow cheese",
        "ham",
        "kulen",
        "lettuce",
        "tomato",
        "fries",

      ],
      "image": "./picturesFoods/Club Sandwich.jpg",
      "tags": ["sandwich"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "mild",
      "customize-options": [],
      "price": 230
    },
    {
      "name": "Classic Toast",
      "macedonian_name": "ТОСТ КЛАСИК",
      "details": "Classic toast with ham, cheese, and sour cream with dill.",
      "ingredients": ["toast bread", "ham", "yellow cheese", "sour cream with dill"],
      "tags": ["toast", "breakfast"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 200,
      "image": "./picturesFoods/Classic Toast.jpg"
    },
    {
      "name": "Sreḱa Toast",
      "macedonian_name": "ТОСТ СРЕЌА",
      "details": "Special 'Sreḱa' toast with kulen, mozzarella, pesto, and arugula.",
      "ingredients": ["toast bread", "kulen", "mozzarella", "pesto", "arugula", "sun-dried tomato"],
      "tags": ["toast", "breakfast", "store-brand"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "mild",
      "customize-options": [],
      "price": 230
    },
    {
      "name": "Vegetarian Sandwich",
      "macedonian_name": "ВЕГЕТАРИЈАНСКИ СЕНДВИЧ",
      "details": "Vegetarian sandwich with sesame bread, guacamole, and mixed vegetables.",
      "ingredients": [
        "homemade sesame bread",
        "guacamole",
        "mixed vegetables (pepper, cucumber, zucchini, tomato, olive, onion)",
        "cheese"
      ],
      "tags": ["sandwich", "vegetarian"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 200
    },
    {
      "name": "Chicken Sandwich",
      "macedonian_name": "ПИЛЕШКИ СЕНДВИЧ",
      "details": "Chicken sandwich with mayonnaise, lettuce, tomato, and Edam cheese.",
      "ingredients": ["mayonnaise", "lettuce", "tomato", "chicken fillet", "Edam cheese"],
      "tags": ["sandwich"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 210
    },
    {
      "name": "Chicken Fingers",
      "macedonian_name": "ПИЛЕШКИ ПРСТИ",
      "details": "Crispy chicken fillet with breadcrumbs and a dressing, served with ribbed fries.",
      "ingredients": ["230g chicken fillet", "breadcrumbs", "dressing", "100g ribbed fries"],
      "tags": [],
      "hasSideDish": true,
      "sideDishes": ["ribbed fries"],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 280
    },
    {
      "name": "Chicken Wings",
      "macedonian_name": "ПИЛЕШКИ КРИЛЦА",
      "details": "Chicken wings with a flavorful sauce consisting of ketchup, cumin, chili, honey, mustard, and pepper.",
      "ingredients": ["chicken wings", "sauce (ketchup, cumin, chili, honey, mustard, pepper)", "oil"],
      "tags": [],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "mild",
      "customize-options": [],
      "price": 0
    },
    {
      "name": "Fries",
      "macedonian_name": "ПОМФРИТ",
      "details": "A mix of ribbed and bakery fries.",
      "ingredients": ["150g ribbed fries", "150g bakery fries"],
      "tags": [],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 260
    },
    {
      "name": "Nachos",
      "macedonian_name": "НАЧОС",
      "details": "Nachos with Edam cheese, mozzarella, cheddar, guacamole sauce, and salsa sauce.",
      "ingredients": ["nachos", "Edam cheese", "mozzarella", "cheddar", "guacamole sauce", "salsa sauce"],
      "tags": [],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "mild",
      "customize-options": [],
      "price": 310
    },
    {
      "name": "Caesar Salad",
      "macedonian_name": "ЦЕЗАР САЛАТА",
      "details": "Classic Caesar salad with lettuce, corn, croutons, chicken fillet, cherry tomatoes, Parmesan, and dressing.",
      "ingredients": ["150g lettuce", "20g corn", "20g croutons", "100g chicken fillet", "20g cherry tomatoes", "20g Parmesan", "40ml dressing"],
      "tags": ["salad"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 270
    },
    {
      "name": "Sreḱa Salad",
      "macedonian_name": "СРЕЌА САЛАТА",
      "details": "Sreḱa salad with iceberg, arugula, carrot, Indian walnuts, dried cranberries, bacon, gorgonzola, and a balsamic dressing.",
      "ingredients": ["100g iceberg lettuce", "100g arugula", "50g carrot", "20g Indian walnuts", "20g dried cranberries", "50g bacon", "20g gorgonzola", "30g dressing", "40ml balsamic cream"],
      "tags": ["salad", "customizable"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": ["iceberg lettuce", "arugula", "carrot", "Indian walnuts", "dried cranberries", "bacon", "gorgonzola", "dressing", "balsamic cream"],
      "price": 280
    },
    {
      "name": "Chicken in Peanut Sauce",
      "macedonian_name": "ПИЛЕШКО ВО КИКИРИКИ СОС",
      "details": "Chicken fillet served with peanut butter sauce, peanuts, and bakery fries.",
      "ingredients": ["220g chicken fillet", "10g peanut butter", "30g peanuts", "200ml cream", "100g bakery fries"],
      "tags": [],
      "hasSideDish": true,
      "sideDishes": ["bakery fries"],
      "spiceLevel": "mild",
      "customize-options": [],
      "price": 310
    },
    {
      "name": "Chicken in 4 Types of Cheese",
      "macedonian_name": "ПИЛЕШКО ВО 4 ВИДА СИРЕЊЕ",
      "details": "Chicken fillet served with mozzarella, gorgonzola, cheddar, and Edam cheese, with bakery fries.",
      "ingredients": ["220g chicken fillet", "20g mozzarella", "20g gorgonzola", "20g cheddar", "20g Edam cheese", "200ml cream", "100g bakery fries"],
      "tags": [],
      "hasSideDish": true,
      "sideDishes": ["bakery fries"],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 330
    },
    {
      "name": "Sreḱa Burger",
      "macedonian_name": "СРЕЌА БУРГЕР",
      "details": "Sreḱa Burger with 100% beef patty, cheddar, caramelized onion, bacon, and a side of bakery fries.",
      "ingredients": ["burger bun", "160g beef patty", "20g iceberg lettuce", "20g cheddar", "20g caramelized onion", "20g bacon", "10g burger sauce", "20g pickles", "100g bakery fries"],
      "tags": ["burger", "customizable"],
      "hasSideDish": true,
      "sideDishes": ["bakery fries"],
      "spiceLevel": "mild",
      "customize-options": ["beef patty", "cheddar", "caramelized onion", "bacon", "burger sauce", "pickles", "bakery fries"],
      "price": 350
    },
    {
      "name": "Vegan Garden Gourmet Burger",
      "macedonian_name": "ВЕГАНСКИ GARDEN GOURMET БУРГЕР",
      "details": "Vegan Garden Gourmet burger with mustard, lettuce, tomato, red onion, pickles, and fries.",
      "ingredients": ["burger bun", "Vegan Garden Gourmet patty", "10g mustard", "20g lettuce", "20g tomato", "20g red onion", "20g pickles", "150g fries"],
      "tags": ["burger", "vegan"],
      "hasSideDish": true,
      "sideDishes": ["fries"],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 280
    },
    {
      "name": "Vegetarian Garden Gourmet Burger",
      "macedonian_name": "ВЕГЕТАРИЈАНСКИ GARDEN GOURMET БУРГЕР",
      "details": "Vegetarian Garden Gourmet burger with sour cream with dill, lettuce, cheddar, caramelized onion, tomato, and bakery fries.",
      "ingredients": ["burger bun", "Vegetarian Garden Gourmet patty", "10g sour cream with dill", "20g lettuce", "20g cheddar", "20g caramelized onion", "10g tomato", "100g bakery fries"],
      "tags": ["burger", "vegetarian"],
      "hasSideDish": true,
      "sideDishes": ["bakery fries"],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 300
    },
    {
      "name": "BBQ Burger",
      "macedonian_name": "BBQ БУРГЕР",
      "details": "BBQ Burger with 100% beef patty, cheddar, crispy onion, bacon, lettuce, tomato, and BBQ sauce.",
      "ingredients": ["burger bun", "160g beef patty", "20g cheddar", "20g crispy onion", "20g bacon", "10g lettuce", "20g tomato", "20g BBQ sauce", "100g bakery fries"],
      "tags": ["burger"],
      "hasSideDish": true,
      "sideDishes": ["bakery fries"],
      "spiceLevel": "mild",
      "customize-options": [],
      "price": 350
    },
    {
      "name": "Snickers Cake",
      "macedonian_name": "СНИКЕРС ТОРТА",
      "details": "A delicious Snickers cake made with whey protein, dates, honey, oats, peanuts, dark chocolate, peanut butter, beef gelatin, and coconut oil.",
      "ingredients": ["whey protein", "dates", "honey", "oats", "peanuts", "dark chocolate", "peanut butter", "beef gelatin", "coconut oil"],
      "tags": [],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 180
    },
    {
      "name": "Pancake",
      "macedonian_name": "ПАЛАЧИНКА",
      "details": "A pancake topped with Nutella, customizable with additional toppings.",
      "ingredients": ["pancake", "100g Nutella"],
      "tags": ["dessert", "customizable"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": ["Plazma", "banana", "raspberry"],
      "price": 140
    },
    {
      "name": "Vegetarian Pizza",
      "macedonian_name": "ВЕГЕТАРИЈАНСКА ПИЦА",
      "details": "Vegetarian pizza with zucchini, red pepper, onion, cherry tomatoes, mushrooms, olives, oregano, and plant-based cheese.",
      "ingredients": ["zucchini", "red pepper", "onion", "cherry tomato", "mushrooms", "olives", "oregano", "plant-based cheese"],
      "tags": ["pizza", "vegetarian"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 310
    },
    {
      "name": "Fresh Orange Juice",
      "macedonian_name": "Цеден Портокал",
      "details": "Freshly squeezed orange juice.",
      "ingredients": ["orange"],
      "tags": ["juice"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 150
    },
    {
      "name": "Fresh Lemon Juice",
      "macedonian_name": "Цеден Лимон",
      "details": "Freshly squeezed lemon juice.",
      "ingredients": ["lemon"],
      "tags": ["juice"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 150
    },
    {
      "name": "Cosmopolitan",
      "macedonian_name": "COSMOPOLITAN",
      "details": "A classic cocktail made with vodka, fresh orange juice, lime, and cranberry.",
      "ingredients": ["vodka", "fresh orange juice", "lime", "cranberry"],
      "tags": ["cocktail"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 250
    },
    {
      "name": "Pina Colada",
      "macedonian_name": "PINA COLADA",
      "details": "A tropical cocktail with rum, coconut cream, and pineapple juice.",
      "ingredients": ["rum", "coconut cream", "pineapple juice"],
      "tags": ["cocktail"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 260
    },
    {
      "name": "Vodka Sour",
      "macedonian_name": "ВОДКА САУР",
      "details": "A sour vodka-based drink.",
      "ingredients": ["vodka", "lemon juice", "sugar syrup"],
      "tags": ["cocktail"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 250
    },
    {
      "name": "Whiskey Sour",
      "macedonian_name": "WHISKEY SOUR",
      "details": "A whiskey-based sour cocktail.",
      "ingredients": ["whiskey", "lemon juice", "sugar syrup"],
      "tags": ["cocktail"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 300
    },
    {
      "name": "Tequila Shot",
      "macedonian_name": "TEQUILA SHOT",
      "details": "A classic shot of tequila.",
      "ingredients": ["tequila"],
      "tags": ["shot"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 100
    },
    {
      "name": "Brain Shot",
      "macedonian_name": "BRAIN SHOT",
      "details": "A layered shot with martini, Baileys, and Monin grenadine.",
      "ingredients": ["martini", "Baileys", "Monin grenadine"],
      "tags": ["shot"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": [],
      "price": 100
    },
    {
      "name": "Protein Shake",
      "macedonian_name": "ПРОТЕИНСКИ ШЕЈК",
      "details": "Protein shake made with whey protein and milk.",
      "ingredients": ["whey protein", "milk"],
      "tags": ["shake", "protein"],
      "hasSideDish": false,
      "sideDishes": [],
      "spiceLevel": "none",
      "customize-options": ["oreo protein", "chocolate protein", "vanilla protein"],
      "price": 110
    }
  ]
  
  
  export default menu_items;