export const listings = [
  {
    company: 'SrekjaMk Filler Company',
    title: 'HR Асистент',
    hours: 30,
    postedDate: 'сега',
    experienceLevel: 'Експерт',
    employmentType: 'Делумно работно време',
    description:
      'Бараме детално-ориентиран HR асистент за поддршка во регрутирање, селекција и координација на кандидати.',
    skills: [
      'Job Posts',
      'Email Communication',
      'Employee Communications',
      'Data Entry',
    ],
    skills_mk: [
      'Објави за работа',
      'Е-пошта комуникација',
      'Комуникација со вработени',
      'Внесување податоци',
    ],
    type: 'Работа',
    tag: 'Човечки ресурси',
  },
  {
    company: 'SrekjaMk Filler Company',
    title: 'Софтверски инженер - Пракса',
    postedDate: 'вчера',
    hours: 40,
    experienceLevel: 'Почетник',
    employmentType: 'Целосно работно време',
    description:
      'Развој и одржување на веб апликации користејќи најнови технологии.',
    skills: ['Software Development', 'JavaScript', 'React', 'Node.js'],
    skills_mk: ['Развој на софтвер', 'JavaScript', 'React', 'Node.js'],
    type: 'Пракса',
    tag: 'ИТ',
  },
  {
    company: 'SrekjaMk Filler Company',
    title: 'Графички дизајнер',
    postedDate: 'вчера',
    hours: 25,
    experienceLevel: 'Почетник',
    employmentType: 'Делумно работно време',
    description:
      'Создавање визуелни концепти и графички елементи за дигитални и печатени медиуми.',
    skills: ['Graphic Design', 'Adobe Photoshop', 'Illustrator', 'Branding'],
    skills_mk: [
      'Графички дизајн',
      'Adobe Photoshop',
      'Illustrator',
      'Брендирање',
    ],
    type: 'Работа',
    tag: 'Дизајн',
  },
  {
    company: 'SrekjaMk Filler Company',
    title: 'Продажен агент',
    postedDate: 'вчера',
    hours: 35,
    experienceLevel: 'Средно',
    employmentType: 'Целосно работно време',
    description: 'Комуникација со клиенти и продажба на производи и услуги.',
    skills: ['Sales', 'Customer Service', 'Negotiation', 'CRM'],
    skills_mk: ['Продажба', 'Услуги за клиенти', 'Преговарање', 'CRM'],
    type: 'Работа',
    tag: 'Продажба',
  },
  {
    company: 'SrekjaMk Filler Company',
    title: 'Маркетинг специјалист',
    postedDate: 'пред 3 дена',
    hours: 40,
    experienceLevel: 'Експерт',
    employmentType: 'Целосно работно време',
    description:
      'Планирање и спроведување маркетинг кампањи за зголемување на бренд свесноста.',
    skills: ['Marketing', 'SEO', 'Content Creation', 'Google Ads'],
    skills_mk: ['Маркетинг', 'SEO', 'Создавање содржина', 'Google Ads'],
    type: 'Работа',
    tag: 'Маркетинг',
  },
  {
    company: 'SrekjaMk Filler Company',
    title: 'Финансиски аналитичар',
    postedDate: 'пред 4 дена',
    hours: 38,
    experienceLevel: 'Средно',
    employmentType: 'Целосно работно време',
    description:
      'Анализа на финансиски извештаи и подготвување стратегии за подобрување на перформансите.',
    skills: ['Finance', 'Data Analysis', 'Excel', 'Budgeting'],
    skills_mk: ['Финансии', 'Анализа на податоци', 'Excel', 'Буџетирање'],
    type: 'Работа',
    tag: 'Финансии',
  },
  {
    company: 'SrekjaMk Filler Company',
    title: 'Техничка поддршка - Пракса',
    postedDate: 'пред 4 дена',
    hours: 30,
    experienceLevel: 'Почетник',
    employmentType: 'Делумно работно време',
    description:
      'Обезбедување техничка поддршка и решавање на ИТ проблеми на корисниците.',
    skills: [
      'Technical Support',
      'Help Desk',
      'Troubleshooting',
      'Customer Service',
    ],
    skills_mk: [
      'Техничка поддршка',
      'Help Desk',
      'Решавање проблеми',
      'Услуги за клиенти',
    ],
    type: 'Пракса',
    tag: 'ИТ',
  },
  {
    company: 'SrekjaMk Filler Company',
    title: 'Административен асистент',
    postedDate: 'пред 6 дена',
    hours: 25,
    experienceLevel: 'Почетник',
    employmentType: 'Делумно работно време',
    description:
      'Организирање документи, закажување состаноци и административни задачи.',
    skills: ['Administration', 'Office Management', 'Data Entry', 'Scheduling'],
    skills_mk: [
      'Администрација',
      'Управување со канцеларија',
      'Внесување податоци',
      'Закажување',
    ],
    type: 'Работа',
    tag: 'Администрација',
  },
  {
    company: 'SrekjaMk Filler Company',
    title: 'Наставник по англиски',
    postedDate: 'пред 1 недела',
    hours: 20,
    experienceLevel: 'Средно',
    employmentType: 'Делумно работно време',
    description: 'Предавање англиски јазик на ученици од различни возрасти.',
    skills: ['Education', 'Teaching', 'Lesson Planning', 'English Language'],
    skills_mk: [
      'Образование',
      'Предавање',
      'Планирање на часови',
      'Англиски јазик',
    ],
    type: 'Работа',
    tag: 'Образование',
  },
  {
    company: 'SrekjaMk Filler Company',
    title: 'Менаџер за човечки ресурси',
    postedDate: 'пред 1 месец',
    hours: 40,
    experienceLevel: 'Експерт',
    employmentType: 'Целосно работно време',
    description:
      'Управување со процесите за регрутација, обука и развој на вработени.',
    skills: [
      'HR',
      'Recruitment',
      'Employee Relations',
      'Performance Management',
    ],
    skills_mk: [
      'Човечки ресурси',
      'Регрутација',
      'Односи со вработени',
      'Управување со перформанси',
    ],
    type: 'Работа',
    tag: 'Човечки ресурси',
  },
];
